name: desplegar en GCP
on:
  push:
    branches:
      - "*"
jobs:
  jod_id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GSP_CREDENTIALS }}"

      - id: "delete-existing"
        name: "Eliminar servicios Existentes"
        run: gcloud run services delete api --region us-central1 --quiet || true

      - id: deploy
        name: "Deploy to GCP"
        uses: "google-github-actions/deploy-cloud-functions@v3"
        timeout-minutes: 10
        with:
          name: "api"
          runtime: "python311"
          entry_point: "hello_http"
